root: true
env:
  node: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
ignorePatterns:
  - dist
  - examples/deno
  - examples/bun
  - coverage
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  project:
    - tsconfig.json
  sourceType: module
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: .
